version: '3'

volumes:
  pg_data_kittygram:
  static_kittygram:
  media_kittygram:


services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_kittygram:/var/lib/postgresql/data
  backend:
    image: nesterovv89/kittygram_backend
    env_file: .env
    volumes:
      - static_kittygram:/backend_static
      - media_kittygram:/app/media/
  frontend:
    env_file: .env
    image: nesterovv89/kittygram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static_kittygram:/static
  gateway:
    image: nesterovv89/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static_kittygram:/static
      - media_kittygram:/media
